/* eslint-disable @typescript-eslint/no-empty-interface */
import { IEntity } from '../../../../geotab/checkmate/object_model/i_entity';
import { IRule } from '../../../../geotab/checkmate/object_model/exceptions/i_rule';
import { MonitorPredicate } from '../../../../geotab/checkmate/object_model/exceptions/monitor_predicate';
import { IDiagnostic } from '../../../../geotab/checkmate/object_model/engine/i_diagnostic';



/**
*  The event of an exception generated by {@link IRuleMonitor} violation.
*
* @deprecated
*/
export interface IRuleMonitor extends IEntity
{
  /** Gets or sets  */
  diagnostic: IDiagnostic;
  /** Gets or sets  */
  monitorPredicate?: MonitorPredicate;
  /** Gets or sets  */
  rule: IRule;
}
