/* eslint-disable @typescript-eslint/no-empty-interface */
import { IEntity } from '../entity';
import { IRule } from '../exceptions/rule';
import { MonitorPredicate } from '../exceptions/monitor_predicate';
import { IDiagnostic } from '../engine/diagnostic';

/**
 *  The event of an exception generated by {@link IRuleMonitor} violation.
 *
 * @deprecated
 */
export interface IRuleMonitor extends IEntity {
  /** Gets or sets  */
  diagnostic: IDiagnostic;
  /** Gets or sets  */
  monitorPredicate?: MonitorPredicate;
  /** Gets or sets  */
  rule: IRule;
}
