/* eslint-disable @typescript-eslint/no-empty-interface */
import { IEntity } from './entity';
import { DebugReason } from './debug_reason';
import { IDevice } from './device';
import { IDriver } from './driver';

/**
 *  DebugData is generated by Geotab GO devices for internal debugging or troubleshooting
 * purposes. This may include information regarding the state of the modem, firmware
 * or conditions that the device is experiencing.
 */
export interface IDebugData extends IEntity {
  /** Gets or sets the binary data. */
  data: number[];
  /** Gets or sets the date and time the DebugData log was created. */
  dateTime?: Date;
  /** Gets or sets the DebugReason; used for troubleshooting/debugging purposes only. */
  debugReason?: DebugReason;
  /** Gets or sets the {@link IDevice} associated with the vehicle. */
  device: IDevice;
  /**
   * Gets or sets the {@link IDriver} of the vehicle at the time the DebugData log entry
   * was created.
   */
  driver: IDriver;
}
