name: build
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 15.x
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: yarn setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  publish:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/heads/main')
    needs: test
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: yarn build
        env:
          CI: true

      - id: publish
        name: publish npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: publish docs
        if: steps.publish.outputs.type != 'none'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/docs

      - name: publish tag
        if: steps.publish.outputs.type != 'none'
        run: |
          git tag ${{ steps.publish.outputs.version }}
          git push -f origin ${{ steps.publish.outputs.version }}
