name: publish
on:
  - workflow_dispatch

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: yarn setup
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn doc
        env:
          CI: true

      - name: github publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/doc

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: yarn publish github
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
