name: test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: yarn setup
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          CI: true
